FROM node as builder
WORKDIR /src
COPY . /src
RUN npm install

FROM alpine@sha256:c74f1b1166784193ea6c8f9440263b9be6cae07dfe35e32a5df7a31358ac2060 as final

RUN apk add --update nodejs

WORKDIR /build

COPY --from=builder /src/ .

ENV PORT=8080
ENV API_URL=http://poker-api

EXPOSE 8080

ENTRYPOINT ["node", "src/index.js"]