version: "3.5"

services:
  poker-web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - poker-api
    ports:
      - target: 80
        published: 80
    environment:
    - PORT=80
    - API_URL=http://poker-api:8080
    networks:
      - backend


  poker-api:
    image: carlschader/poker-api:latest
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - target: 8080
        published: 8080

  populate-redis:
    image: carlschader/poker-populate-redis:latest
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - target: 6379
        published: 6379
    networks:
      - backend
    volumes:
      - redis:/data

networks:
  backend:

volumes:
  redis: