version: "3.5"

services:
  poker-web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - poker-go-api
    ports:
      - target: 80
        published: 80
    environment:
    - PORT=80
    - API_URL=http://poker-go-api:8080
    networks:
      - backend


  poker-go-api:
    image: carlschader/poker-go-api:latest
    depends_on:
      - mongo
      - create-ranks
    networks:
      - backend
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=poker
      - RANKS_COLLECTION_NAME=ranks
      - CACHE_COLLECTION_NAME=cache
      - CALCULATION_TIMEOUT=120
    ports:
      - target: 8080
        published: 8080
  
  create-ranks:
    image: carlschader/poker-create-ranks:latest
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=poker
      - RANKS_COLLECTION_NAME=ranks
      - CACHE_COLLECTION_NAME=cache
      - BATCHES=1
  
  create-pockets:
    image: carlschader/poker-create-pockets:latest
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=poker
      - POCKETS_COLLECTION_NAME=pockets

  mongo:
    image: mongo
    ports:
      - target: 27017
        published: 27017
    networks:
      - backend
    volumes:
      - mongo:/data/db



networks:
  backend:

volumes:
  mongo: