FROM node as builder
WORKDIR /src
COPY . /src
RUN npm install

FROM alpine@sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3 as final

RUN apk add --update nodejs

WORKDIR /build

COPY --from=builder /src/ .

ENV PORT=8080
ENV API_URL=http://poker-api

EXPOSE 8080

ENTRYPOINT ["node", "src/index.js"]