apiVersion: v1
kind: Pod
metadata:
  name: poker-web
spec:
  containers:
    - image: carlschader/poker-web:amd
      name: poker-web
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 5
        periodSeconds: 60
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP